# Generated by Django 3.1.2 on 2020-12-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPrincipales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=120)),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '1.1 Datos de la Aplicación',
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='icon-lightbulb', max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('contenido', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '1.2 Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos')),
                ('color_interfaz', models.CharField(choices=[('/static/css/colors/green.css', 'Verde'), ('/static/css/colors/mossgreen.css', 'Verde Mostaza'), ('/static/css/colors/bridge.css', 'Verde Claro'), ('/static/css/colors/orange.css', 'Naranja'), ('/static/css/colors/pink.css', 'Rosado'), ('/static/css/colors/red.css', 'Rojo'), ('/static/css/colors/purple.css', 'Morado'), ('/static/css/colors/yellow.css', 'Amarillo'), ('/static/css/colors/violet.css', 'Violeta'), ('/static/css/colors/cyan.css', 'Cyan'), ('/static/css/colors/azul.css', 'Azul')], default='Verde', max_length=100)),
                ('video_fondo', models.CharField(default='J2qDRJdTGow', max_length=120)),
            ],
            options={
                'verbose_name_plural': '1. Página Principal',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(choices=[('HOME', 'HOME'), ('PYMES', 'PYMES')], max_length=30)),
                ('descripcion', models.TextField(max_length=200)),
                ('detalle', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': '2. Servicios',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Slider')),
                ('frase1', models.CharField(max_length=100)),
                ('posicion_frase1', models.IntegerField(default=50)),
                ('frase2', models.CharField(max_length=100)),
                ('posicion_frase2', models.IntegerField(default=50)),
                ('texto_decorativo', models.CharField(max_length=100)),
                ('posicion_texto_decorativo', models.IntegerField(default=50)),
                ('izquierda', models.BooleanField(default=True)),
                ('derecha', models.BooleanField(default=False)),
                ('centro', models.BooleanField(default=False)),
                ('duracion', models.IntegerField(default=9)),
                ('text_size', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': '1.2 Sliders',
            },
        ),
        migrations.CreateModel(
            name='Pymes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='icon-lightbulb', max_length=30)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.servicios')),
            ],
            options={
                'verbose_name_plural': '2.2 Pymes',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='icon-lightbulb', max_length=30)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.servicios')),
            ],
            options={
                'verbose_name_plural': '2.1 Home',
            },
        ),
    ]
