# Generated by Django 3.1.4 on 2021-02-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_home_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosprincipales',
            name='whatsapp',
        ),
    ]
