# Generated by Django 3.1.4 on 2021-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_datosprincipales_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosprincipales',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
