# Generated by Django 3.1.4 on 2021-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_datosprincipales_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('megas', models.CharField(max_length=10)),
                ('Precio', models.CharField(max_length=10)),
                ('simetrico', models.CharField(max_length=10)),
                ('comparticion', models.CharField(max_length=10)),
                ('dispositivos', models.CharField(max_length=20)),
                ('juegosmoviles', models.CharField(max_length=20)),
                ('juegosonline', models.CharField(max_length=20)),
                ('netflix', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '2.3 Planes',
            },
        ),
    ]
