# Generated by Django 3.1.4 on 2021-02-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_planes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='icono',
            field=models.CharField(max_length=20),
        ),
    ]
