# Generated by Django 3.1.4 on 2021-02-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20210223_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planes',
            old_name='Precio',
            new_name='precio',
        ),
    ]
