# Generated by Django 3.1.4 on 2021-02-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20210223_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='info',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
