# Generated by Django 3.1.4 on 2021-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_planes_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='simetrico',
        ),
        migrations.AddField(
            model_name='planes',
            name='conexion',
            field=models.CharField(default='Simétrica', max_length=20),
        ),
        migrations.AlterField(
            model_name='planes',
            name='comparticion',
            field=models.CharField(default='1:1', max_length=10),
        ),
        migrations.AlterField(
            model_name='planes',
            name='dispositivos',
            field=models.CharField(choices=[('1/4', '1/4'), ('1/8', '1/8'), ('1/15', '1/15'), ('1/25', '1/25')], max_length=20),
        ),
        migrations.AlterField(
            model_name='planes',
            name='icono',
            field=models.CharField(choices=[('fa fa-home', 'fa fa-home'), ('fa fa-archive', 'fa fa-archive'), ('fa fa-gamepad', 'fa fa-gamepad'), ('fa fa-camera', 'fa fa-camera')], max_length=20),
        ),
        migrations.AlterField(
            model_name='planes',
            name='megas',
            field=models.CharField(choices=[('20 Mbps', '20 Mbps'), ('30 Mbps', '30 Mbps'), ('60 Mbps', '60 Mbps'), ('100 Mbps', '100 Mbps')], max_length=20),
        ),
        migrations.AlterField(
            model_name='planes',
            name='nombre',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Standard', 'Standard'), ('Premiun', 'Premium'), ('Experto', 'Experto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='planes',
            name='precio',
            field=models.CharField(choices=[('20.00', '20.00'), ('25.00', '25.00'), ('35.00', '35.00'), ('60.00', '60.00')], max_length=10),
        ),
    ]
