# Generated by Django 3.1.4 on 2021-02-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20210223_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='detalle',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
