# Generated by Django 3.1.4 on 2021-02-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_home_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('concepto', models.TextField(max_length=200)),
                ('nota', models.TextField(max_length=60)),
                ('imagen', models.ImageField(upload_to='Aplicacion')),
            ],
            options={
                'verbose_name_plural': '2.2 Aplicación',
            },
        ),
        migrations.CreateModel(
            name='Aplicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=200)),
                ('imagen', models.ImageField(upload_to='Aplicaciones')),
            ],
            options={
                'verbose_name_plural': '2.3 Aplicaciones',
            },
        ),
        migrations.CreateModel(
            name='Caracteriticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=200)),
                ('imagen', models.ImageField(upload_to='Home')),
            ],
            options={
                'verbose_name_plural': '2.1 Características',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('concepto', models.TextField(max_length=200)),
                ('nota', models.TextField(max_length=60)),
                ('imagen', models.ImageField(upload_to='Servicio')),
            ],
            options={
                'verbose_name_plural': '2. Servicio',
            },
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Pymes',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
