# Generated by Django 3.1.4 on 2021-02-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20210226_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=200)),
                ('imagen', models.ImageField(upload_to='Detalles')),
            ],
            options={
                'verbose_name_plural': '2.1 Detalles Servicio',
            },
        ),
        migrations.DeleteModel(
            name='Caracteriticas',
        ),
    ]
