# Generated by Django 3.1.4 on 2021-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20210226_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles',
            name='icono',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalles',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Detalles'),
        ),
    ]
