# Generated by Django 3.1.4 on 2021-03-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20210303_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planes',
            options={'verbose_name_plural': '2.4 Planes'},
        ),
        migrations.RemoveField(
            model_name='aplicacion',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='aplicaciones',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='aplicaciones',
            name='titulo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='detalles',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='detalles',
            name='titulo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
