# Generated by Django 3.1.4 on 2021-03-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_auto_20210320_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=200)),
                ('icono', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': '2.3 Características',
            },
        ),
        migrations.AlterModelOptions(
            name='aplicaciones',
            options={'verbose_name_plural': '2.5 Aplicaciones'},
        ),
        migrations.RemoveField(
            model_name='aplicaciones',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='aplicaciones',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='detalles',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='detalles',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='detalles',
            name='titulo',
        ),
    ]
