# Generated by Django 3.1.4 on 2021-03-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_auto_20210320_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Nosotros'),
        ),
    ]
