# Generated by Django 3.1.4 on 2021-03-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_auto_20210322_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('titulo2', models.CharField(blank=True, max_length=30, null=True)),
                ('titulo3', models.CharField(blank=True, max_length=30, null=True)),
                ('concepto', models.TextField(max_length=200)),
                ('nota', models.TextField(max_length=60)),
                ('imagen', models.ImageField(upload_to='Datos')),
            ],
            options={
                'verbose_name_plural': '2.2 Datos Servicio',
            },
        ),
        migrations.CreateModel(
            name='Detalles_Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(choices=[('fa fa-home', 'fa fa-home'), ('fa fa-archive', 'fa fa-archive'), ('fa fa-gamepad', 'fa fa-gamepad'), ('fa fa-camera', 'fa fa-camera')], max_length=20)),
                ('nombre', models.CharField(choices=[('Básico', 'Básico'), ('Standard', 'Standard'), ('Premiun', 'Premium'), ('Experto', 'Experto')], max_length=20)),
                ('megas', models.CharField(choices=[('20 Mbps', '20 Mbps'), ('30 Mbps', '30 Mbps'), ('60 Mbps', '60 Mbps'), ('100 Mbps', '100 Mbps')], max_length=20)),
                ('precio', models.CharField(choices=[('20.00', '20.00'), ('25.00', '25.00'), ('35.00', '35.00'), ('60.00', '60.00')], max_length=10)),
                ('conexion', models.CharField(default='Simétrica', max_length=20)),
                ('comparticion', models.CharField(default='1:1', max_length=10)),
                ('dispositivos', models.CharField(choices=[('1/4', '1/4'), ('5/8', '5/8'), ('9/15', '9/15'), ('10/25', '10/25')], max_length=20)),
                ('juegosmoviles', models.CharField(max_length=20)),
                ('juegosonline', models.CharField(max_length=20)),
                ('netflix', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '3.1 Detalle Planes',
            },
        ),
        migrations.RenameModel(
            old_name='Aplicaciones',
            new_name='Aplicacion_Planes',
        ),
        migrations.RenameModel(
            old_name='Caracteristicas',
            new_name='Metricas',
        ),
        migrations.DeleteModel(
            name='Aplicacion',
        ),
        migrations.AlterModelOptions(
            name='aplicacion_planes',
            options={'verbose_name_plural': '3.2 Aplicación Planes'},
        ),
        migrations.AlterModelOptions(
            name='cobertura',
            options={'verbose_name_plural': '2.4 Cobertura'},
        ),
        migrations.AlterModelOptions(
            name='metricas',
            options={'verbose_name_plural': '2.3 Métricas'},
        ),
        migrations.AlterModelOptions(
            name='planes',
            options={'verbose_name_plural': '3. Planes'},
        ),
        migrations.RemoveField(
            model_name='planes',
            name='comparticion',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='conexion',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='dispositivos',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='juegosmoviles',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='juegosonline',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='megas',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='netflix',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='contacto1',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='nosotros',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='nosotros1',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='planes',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='planes1',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='planes2',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='planes3',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='promos',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='promos1',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='servicio1',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='servicio2',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='servicio3',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='servicio4',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='servicio5',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='servicio6',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='servicio7',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='servicio8',
        ),
        migrations.AddField(
            model_name='planes',
            name='concepto',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Planes'),
        ),
        migrations.AddField(
            model_name='planes',
            name='nota',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='titulo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='titulo2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='titulo3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='icono',
            field=models.CharField(max_length=30),
        ),
    ]
