# Generated by Django 3.1.4 on 2021-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_auto_20210322_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPlanes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(choices=[('fa fa-home', 'fa fa-home'), ('fa fa-archive', 'fa fa-archive'), ('fa fa-gamepad', 'fa fa-gamepad'), ('fa fa-camera', 'fa fa-camera')], max_length=20)),
                ('nombre', models.CharField(choices=[('Básico', 'Básico'), ('Standard', 'Standard'), ('Premiun', 'Premium'), ('Experto', 'Experto')], max_length=20)),
                ('megas', models.CharField(choices=[('20 Mbps', '20 Mbps'), ('30 Mbps', '30 Mbps'), ('60 Mbps', '60 Mbps'), ('100 Mbps', '100 Mbps')], max_length=20)),
                ('precio', models.CharField(choices=[('20.00', '20.00'), ('25.00', '25.00'), ('35.00', '35.00'), ('60.00', '60.00')], max_length=10)),
                ('conexion', models.CharField(default='Simétrica', max_length=20)),
                ('comparticion', models.CharField(default='1:1', max_length=10)),
                ('dispositivos', models.CharField(choices=[('4', '4'), ('8', '8'), ('15', '15'), ('25', '25')], max_length=20)),
                ('info', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '3.1 Lista Planes',
            },
        ),
        migrations.CreateModel(
            name='Sitios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=40)),
                ('Nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': '2.3 Sitios',
            },
        ),
        migrations.RenameModel(
            old_name='Aplicacion_Planes',
            new_name='Aplicaciones',
        ),
        migrations.RenameModel(
            old_name='Detalles',
            new_name='Caracteristicas',
        ),
        migrations.DeleteModel(
            name='Datos',
        ),
        migrations.DeleteModel(
            name='Detalles_Planes',
        ),
        migrations.AlterModelOptions(
            name='aplicaciones',
            options={'verbose_name_plural': '3.2 Aplicaciones Planes'},
        ),
        migrations.AlterModelOptions(
            name='caracteristicas',
            options={'verbose_name_plural': '2.1 Características'},
        ),
        migrations.AlterModelOptions(
            name='cobertura',
            options={'verbose_name_plural': '2.2 Cobertura'},
        ),
        migrations.RenameField(
            model_name='cobertura',
            old_name='Nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='cobertura',
            name='icono',
        ),
        migrations.AddField(
            model_name='cobertura',
            name='concepto',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cobertura',
            name='imagen',
            field=models.ImageField(default=1, upload_to='Datos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cobertura',
            name='nota',
            field=models.TextField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cobertura',
            name='titulo2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cobertura',
            name='titulo3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
