# Generated by Django 3.1.4 on 2021-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_auto_20210323_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Promociones')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('contenido', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Promociones',
            },
        ),
        migrations.AlterModelOptions(
            name='nosotros',
            options={'verbose_name_plural': '5. Nosotros'},
        ),
        migrations.AlterModelOptions(
            name='sitios',
            options={'verbose_name_plural': '2.4 Sitios'},
        ),
    ]
