# Generated by Django 3.1.4 on 2021-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_auto_20210324_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodusnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('titulo2', models.CharField(blank=True, max_length=30, null=True)),
                ('titulo3', models.CharField(blank=True, max_length=30, null=True)),
                ('concepto', models.TextField(max_length=400)),
                ('nota', models.TextField(max_length=100)),
                ('imagen', models.ImageField(upload_to='Nodusnet')),
            ],
            options={
                'verbose_name_plural': '5. Nodusnet',
            },
        ),
        migrations.AlterModelOptions(
            name='nosotros',
            options={'verbose_name_plural': '5.1 Nosotros'},
        ),
        migrations.RemoveField(
            model_name='nosotros',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='contenido',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
